### ISSUE TITLE
feature/aarch64-port is not compiling

### ISSUE THREAD

**Issue by markfirmware** [ZystemOS/pluto#234] opened 2020-09-10 00:30 UTC
zig version
    0.6.0+749417a1fzig
    build run -Daarch64-freestanding -Ddisable-display
    ./test/runtime_test.zig:220:26: error: container 'std.linked_list.Node' has no member called 'init'
            node.* = Node.init(line);

I do not know enough about the build.zig design to diagnose this further.

**Comment by SamTebbs33** [comment] 2020-09-10 17:47
This is caused by changes to the std lib that we haven't incorporated into the branch yet. I'm pretty sure that I actually updated this on develop a little while ago so I'll rebase feature/aarch64-port and force push to get those changes in. Cheers.

**Comment by SamTebbs33** [comment] 2020-09-10 18:07
Done! Closed by 8888278

**Closed as completed by SamTebbs33** 2020-09-10 18:07 UTC
Labels: building, arch: aarch64

**Comment by markfirmware** [comment] 2020-09-10 18:08
Thanks!
